#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 49
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_doc_comment_block = 2,
  sym_line_comment = 3,
  anon_sym_pub = 4,
  anon_sym_let = 5,
  anon_sym_COLON = 6,
  anon_sym_EQ = 7,
  anon_sym_struct = 8,
  anon_sym_enum = 9,
  anon_sym_abstract = 10,
  anon_sym_fn = 11,
  anon_sym_EQ_GT = 12,
  anon_sym_using = 13,
  anon_sym_impl = 14,
  anon_sym_for = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_SEMI = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  anon_sym_if = 24,
  anon_sym_unless = 25,
  anon_sym_then = 26,
  anon_sym_elif = 27,
  anon_sym_elunless = 28,
  anon_sym_else = 29,
  anon_sym_in = 30,
  anon_sym_do = 31,
  anon_sym_while = 32,
  anon_sym_until = 33,
  anon_sym_scope = 34,
  anon_sym_loop = 35,
  anon_sym_return = 36,
  anon_sym_yield = 37,
  anon_sym_restart = 38,
  anon_sym_continue = 39,
  anon_sym_break = 40,
  aux_sym_string_token1 = 41,
  aux_sym_string_token2 = 42,
  anon_sym_bool = 43,
  anon_sym_i32 = 44,
  anon_sym_u32 = 45,
  anon_sym_u8 = 46,
  anon_sym_true = 47,
  anon_sym_false = 48,
  sym_source_file = 49,
  sym_expressions = 50,
  sym_expression = 51,
  sym_declaration = 52,
  sym_decl_let = 53,
  sym_decl_struct = 54,
  sym_decl_enum = 55,
  sym_decl_fn = 56,
  sym_decl_using = 57,
  sym_symbol_ref = 58,
  sym_semicolon_grouping = 59,
  sym_expression_list_comma = 60,
  sym_expression_list_semicolon = 61,
  sym_decl_struct_body = 62,
  sym_decl_enum_body = 63,
  sym__control_flow = 64,
  sym_return = 65,
  sym_yield = 66,
  sym_restart = 67,
  sym_continue = 68,
  sym_string = 69,
  aux_sym_expression_list_comma_repeat1 = 70,
  aux_sym_expression_list_semicolon_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_doc_comment_block] = "doc_comment_block",
  [sym_line_comment] = "line_comment",
  [anon_sym_pub] = "pub",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_abstract] = "abstract",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_using] = "using",
  [anon_sym_impl] = "impl",
  [anon_sym_for] = "for",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_if] = "if",
  [anon_sym_unless] = "unless",
  [anon_sym_then] = "then",
  [anon_sym_elif] = "elif",
  [anon_sym_elunless] = "elunless",
  [anon_sym_else] = "else",
  [anon_sym_in] = "in",
  [anon_sym_do] = "do",
  [anon_sym_while] = "while",
  [anon_sym_until] = "until",
  [anon_sym_scope] = "scope",
  [anon_sym_loop] = "loop",
  [anon_sym_return] = "return",
  [anon_sym_yield] = "yield",
  [anon_sym_restart] = "restart",
  [anon_sym_continue] = "continue",
  [anon_sym_break] = "break",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_bool] = "bool",
  [anon_sym_i32] = "i32",
  [anon_sym_u32] = "u32",
  [anon_sym_u8] = "u8",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_expressions] = "expressions",
  [sym_expression] = "expression",
  [sym_declaration] = "declaration",
  [sym_decl_let] = "decl_let",
  [sym_decl_struct] = "decl_struct",
  [sym_decl_enum] = "decl_enum",
  [sym_decl_fn] = "decl_fn",
  [sym_decl_using] = "decl_using",
  [sym_symbol_ref] = "symbol_ref",
  [sym_semicolon_grouping] = "semicolon_grouping",
  [sym_expression_list_comma] = "expression_list_comma",
  [sym_expression_list_semicolon] = "expression_list_semicolon",
  [sym_decl_struct_body] = "decl_struct_body",
  [sym_decl_enum_body] = "decl_enum_body",
  [sym__control_flow] = "_control_flow",
  [sym_return] = "return",
  [sym_yield] = "yield",
  [sym_restart] = "restart",
  [sym_continue] = "continue",
  [sym_string] = "string",
  [aux_sym_expression_list_comma_repeat1] = "expression_list_comma_repeat1",
  [aux_sym_expression_list_semicolon_repeat1] = "expression_list_semicolon_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_doc_comment_block] = sym_doc_comment_block,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_elunless] = anon_sym_elunless,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_until] = anon_sym_until,
  [anon_sym_scope] = anon_sym_scope,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_yield] = anon_sym_yield,
  [anon_sym_restart] = anon_sym_restart,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_break] = anon_sym_break,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_expressions] = sym_expressions,
  [sym_expression] = sym_expression,
  [sym_declaration] = sym_declaration,
  [sym_decl_let] = sym_decl_let,
  [sym_decl_struct] = sym_decl_struct,
  [sym_decl_enum] = sym_decl_enum,
  [sym_decl_fn] = sym_decl_fn,
  [sym_decl_using] = sym_decl_using,
  [sym_symbol_ref] = sym_symbol_ref,
  [sym_semicolon_grouping] = sym_semicolon_grouping,
  [sym_expression_list_comma] = sym_expression_list_comma,
  [sym_expression_list_semicolon] = sym_expression_list_semicolon,
  [sym_decl_struct_body] = sym_decl_struct_body,
  [sym_decl_enum_body] = sym_decl_enum_body,
  [sym__control_flow] = sym__control_flow,
  [sym_return] = sym_return,
  [sym_yield] = sym_yield,
  [sym_restart] = sym_restart,
  [sym_continue] = sym_continue,
  [sym_string] = sym_string,
  [aux_sym_expression_list_comma_repeat1] = aux_sym_expression_list_comma_repeat1,
  [aux_sym_expression_list_semicolon_repeat1] = aux_sym_expression_list_semicolon_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elunless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_until] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scope] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yield] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_restart] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expressions] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_let] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_using] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_semicolon_grouping] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_list_comma] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_list_semicolon] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_enum_body] = {
    .visible = true,
    .named = true,
  },
  [sym__control_flow] = {
    .visible = false,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_yield] = {
    .visible = true,
    .named = true,
  },
  [sym_restart] = {
    .visible = true,
    .named = true,
  },
  [sym_continue] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_expression_list_comma_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_list_semicolon_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_import = 2,
  field_initializer = 3,
  field_name = 4,
  field_type = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_import] = "import",
  [field_initializer] = "initializer",
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_import, 1},
  [2] =
    {field_value, 1},
  [3] =
    {field_name, 1},
    {field_type, 3},
  [5] =
    {field_initializer, 3},
    {field_name, 1},
  [7] =
    {field_body, 3},
    {field_name, 1},
  [9] =
    {field_initializer, 5},
    {field_name, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 3,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 8,
  [17] = 10,
  [18] = 18,
  [19] = 19,
  [20] = 18,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 23,
  [27] = 25,
  [28] = 24,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 32,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 33,
  [58] = 35,
  [59] = 38,
  [60] = 37,
  [61] = 41,
  [62] = 62,
  [63] = 52,
  [64] = 44,
  [65] = 65,
  [66] = 36,
  [67] = 46,
  [68] = 50,
  [69] = 69,
  [70] = 70,
  [71] = 56,
  [72] = 55,
  [73] = 54,
  [74] = 74,
  [75] = 69,
  [76] = 53,
  [77] = 51,
  [78] = 43,
  [79] = 49,
  [80] = 42,
  [81] = 48,
  [82] = 82,
  [83] = 82,
  [84] = 74,
  [85] = 47,
  [86] = 39,
  [87] = 40,
  [88] = 88,
  [89] = 89,
  [90] = 88,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 100,
  [104] = 104,
  [105] = 105,
  [106] = 91,
  [107] = 101,
  [108] = 102,
  [109] = 104,
  [110] = 93,
  [111] = 94,
  [112] = 98,
  [113] = 105,
  [114] = 99,
  [115] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 23,
        '#', 10,
        '(', 15,
        ')', 16,
        ',', 17,
        ':', 12,
        ';', 18,
        '=', 13,
        '[', 21,
        ']', 22,
        '{', 19,
        '}', 20,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(1);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_doc_comment_block);
      if (lookahead == '#') ADVANCE(2);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_doc_comment_block);
      if (lookahead == '#') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(27);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(27);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(27);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(27);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(27);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'l', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
        'u', 13,
        'w', 14,
        'y', 15,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'b') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '3') ADVANCE(26);
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'm') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(34);
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == '3') ADVANCE(38);
      if (lookahead == '8') ADVANCE(39);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 's') ADVANCE(49);
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 26:
      if (lookahead == '2') ADVANCE(54);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(55);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 32:
      if (lookahead == 'b') ADVANCE(58);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(59);
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(64);
      END_STATE();
    case 38:
      if (lookahead == '2') ADVANCE(65);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 48:
      if (lookahead == 'f') ADVANCE(75);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 51:
      if (lookahead == 'm') ADVANCE(78);
      END_STATE();
    case 52:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 57:
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 60:
      if (lookahead == 'u') ADVANCE(83);
      END_STATE();
    case 61:
      if (lookahead == 'p') ADVANCE(84);
      END_STATE();
    case 62:
      if (lookahead == 'u') ADVANCE(85);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(86);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(91);
      END_STATE();
    case 70:
      if (lookahead == 'l') ADVANCE(92);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 73:
      if (lookahead == 'k') ADVANCE(94);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(95);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 77:
      if (lookahead == 'l') ADVANCE(96);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 82:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 83:
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 84:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 85:
      if (lookahead == 'c') ADVANCE(101);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 88:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 89:
      if (lookahead == 'l') ADVANCE(103);
      END_STATE();
    case 90:
      if (lookahead == 'g') ADVANCE(104);
      END_STATE();
    case 91:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 92:
      if (lookahead == 'd') ADVANCE(106);
      END_STATE();
    case 93:
      if (lookahead == 'a') ADVANCE(107);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(110);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(111);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_scope);
      END_STATE();
    case 101:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 102:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_until);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_yield);
      END_STATE();
    case 107:
      if (lookahead == 'c') ADVANCE(114);
      END_STATE();
    case 108:
      if (lookahead == 'u') ADVANCE(115);
      END_STATE();
    case 109:
      if (lookahead == 's') ADVANCE(116);
      END_STATE();
    case 110:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 114:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 115:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 116:
      if (lookahead == 's') ADVANCE(120);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_restart);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_elunless);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 25},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 25},
  [115] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_doc_comment_block] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_elunless] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_until] = ACTIONS(1),
    [anon_sym_scope] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_yield] = ACTIONS(1),
    [anon_sym_restart] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(97),
    [sym_expressions] = STATE(96),
    [sym_expression] = STATE(75),
    [sym_declaration] = STATE(79),
    [sym_decl_let] = STATE(81),
    [sym_decl_struct] = STATE(81),
    [sym_decl_enum] = STATE(81),
    [sym_decl_fn] = STATE(81),
    [sym_decl_using] = STATE(81),
    [sym_symbol_ref] = STATE(79),
    [sym_semicolon_grouping] = STATE(79),
    [sym_expression_list_semicolon] = STATE(95),
    [sym__control_flow] = STATE(79),
    [sym_return] = STATE(79),
    [sym_yield] = STATE(79),
    [sym_restart] = STATE(79),
    [sym_continue] = STATE(79),
    [sym_string] = STATE(79),
    [sym_identifier] = ACTIONS(7),
    [sym_doc_comment_block] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_pub] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_struct] = ACTIONS(13),
    [anon_sym_enum] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_using] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_yield] = ACTIONS(25),
    [anon_sym_restart] = ACTIONS(27),
    [anon_sym_continue] = ACTIONS(29),
    [aux_sym_string_token1] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(39), 1,
      sym_expression,
    ACTIONS(39), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [74] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(47), 1,
      sym_expression,
    ACTIONS(61), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [148] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(38), 1,
      sym_expression,
    ACTIONS(63), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [222] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(86), 1,
      sym_expression,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [294] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(59), 1,
      sym_expression,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [366] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(85), 1,
      sym_expression,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [438] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [508] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [578] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(69), 1,
      sym_expression,
    STATE(102), 1,
      sym_expression_list_semicolon,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [648] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(70), 1,
      sym_expression,
    STATE(98), 1,
      sym_expression_list_comma,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [718] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [788] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(70), 1,
      sym_expression,
    STATE(112), 1,
      sym_expression_list_comma,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [858] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    ACTIONS(69), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [928] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [998] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1068] = 19,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(69), 1,
      sym_expression,
    STATE(108), 1,
      sym_expression_list_semicolon,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1138] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(90), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1205] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(89), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1272] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(88), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1339] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(36), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1406] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(66), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1473] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(61), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1540] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(55), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1607] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(54), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1674] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_pub,
    ACTIONS(37), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      anon_sym_struct,
    ACTIONS(43), 1,
      anon_sym_enum,
    ACTIONS(45), 1,
      anon_sym_fn,
    ACTIONS(47), 1,
      anon_sym_using,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_yield,
    ACTIONS(55), 1,
      anon_sym_restart,
    ACTIONS(57), 1,
      anon_sym_continue,
    ACTIONS(59), 1,
      aux_sym_string_token1,
    STATE(41), 1,
      sym_expression,
    STATE(48), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(49), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1741] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(73), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1808] = 18,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_pub,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_struct,
    ACTIONS(15), 1,
      anon_sym_enum,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_using,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_yield,
    ACTIONS(27), 1,
      anon_sym_restart,
    ACTIONS(29), 1,
      anon_sym_continue,
    ACTIONS(31), 1,
      aux_sym_string_token1,
    STATE(72), 1,
      sym_expression,
    STATE(81), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
    STATE(79), 9,
      sym_declaration,
      sym_symbol_ref,
      sym_semicolon_grouping,
      sym__control_flow,
      sym_return,
      sym_yield,
      sym_restart,
      sym_continue,
      sym_string,
  [1875] = 8,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(73), 1,
      anon_sym_let,
    ACTIONS(75), 1,
      anon_sym_struct,
    ACTIONS(77), 1,
      anon_sym_enum,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      anon_sym_using,
    STATE(60), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
  [1904] = 8,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_let,
    ACTIONS(85), 1,
      anon_sym_struct,
    ACTIONS(87), 1,
      anon_sym_enum,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      anon_sym_using,
    STATE(37), 5,
      sym_decl_let,
      sym_decl_struct,
      sym_decl_enum,
      sym_decl_fn,
      sym_decl_using,
  [1933] = 6,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      anon_sym_LBRACK,
    STATE(42), 1,
      sym_decl_struct_body,
    ACTIONS(93), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1956] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_decl_enum_body,
    ACTIONS(99), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1976] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(105), 1,
      anon_sym_EQ,
    ACTIONS(107), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1995] = 6,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    STATE(80), 1,
      sym_decl_struct_body,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2016] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(113), 1,
      anon_sym_EQ,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(117), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2035] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(119), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2049] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(121), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2063] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(123), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2077] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(125), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2091] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(127), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2105] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(129), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2119] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(131), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2133] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(133), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2147] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(135), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2161] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_decl_enum_body,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2179] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(139), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2193] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(141), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2207] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(143), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2221] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(145), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2235] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(147), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2249] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(149), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2263] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(151), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2277] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(153), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2291] = 4,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(155), 1,
      anon_sym_EQ,
    ACTIONS(157), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2307] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(159), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2321] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(161), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2335] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(165), 1,
      anon_sym_EQ,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2352] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(113), 1,
      anon_sym_EQ,
    ACTIONS(167), 1,
      anon_sym_EQ_GT,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2369] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2381] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2393] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2405] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      aux_sym_expression_list_comma_repeat1,
  [2421] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2433] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2445] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_expression_list_comma_repeat1,
  [2461] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2473] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2485] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(147), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2497] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      aux_sym_expression_list_semicolon_repeat1,
  [2513] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      aux_sym_expression_list_comma_repeat1,
  [2529] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2541] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(159), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2553] = 4,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(184), 1,
      anon_sym_EQ,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2567] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(188), 1,
      anon_sym_SEMI,
    STATE(74), 1,
      aux_sym_expression_list_semicolon_repeat1,
  [2583] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    STATE(83), 1,
      aux_sym_expression_list_semicolon_repeat1,
  [2599] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2611] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2623] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2635] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2647] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2659] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2671] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      aux_sym_expression_list_semicolon_repeat1,
  [2687] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 1,
      anon_sym_SEMI,
    STATE(74), 1,
      aux_sym_expression_list_semicolon_repeat1,
  [2703] = 5,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(197), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      aux_sym_expression_list_semicolon_repeat1,
  [2719] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2731] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(125), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2743] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_SEMI,
  [2755] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2766] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(172), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2777] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(186), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [2788] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(200), 1,
      sym_identifier,
  [2798] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(202), 1,
      sym_identifier,
  [2808] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
  [2818] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
  [2828] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
  [2838] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
  [2848] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
  [2858] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
  [2868] = 2,
    ACTIONS(216), 1,
      aux_sym_string_token2,
    ACTIONS(5), 2,
      sym_doc_comment_block,
      sym_line_comment,
  [2876] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(218), 1,
      sym_identifier,
  [2886] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(220), 1,
      sym_identifier,
  [2896] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
  [2906] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(224), 1,
      sym_identifier,
  [2916] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(226), 1,
      aux_sym_string_token1,
  [2926] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(228), 1,
      sym_identifier,
  [2936] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(230), 1,
      sym_identifier,
  [2946] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(232), 1,
      sym_identifier,
  [2956] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
  [2966] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(236), 1,
      aux_sym_string_token1,
  [2976] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
  [2986] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
  [2996] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(242), 1,
      anon_sym_RBRACK,
  [3006] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(244), 1,
      sym_identifier,
  [3016] = 2,
    ACTIONS(246), 1,
      aux_sym_string_token2,
    ACTIONS(5), 2,
      sym_doc_comment_block,
      sym_line_comment,
  [3024] = 3,
    ACTIONS(3), 1,
      sym_doc_comment_block,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(248), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 74,
  [SMALL_STATE(4)] = 148,
  [SMALL_STATE(5)] = 222,
  [SMALL_STATE(6)] = 294,
  [SMALL_STATE(7)] = 366,
  [SMALL_STATE(8)] = 438,
  [SMALL_STATE(9)] = 508,
  [SMALL_STATE(10)] = 578,
  [SMALL_STATE(11)] = 648,
  [SMALL_STATE(12)] = 718,
  [SMALL_STATE(13)] = 788,
  [SMALL_STATE(14)] = 858,
  [SMALL_STATE(15)] = 928,
  [SMALL_STATE(16)] = 998,
  [SMALL_STATE(17)] = 1068,
  [SMALL_STATE(18)] = 1138,
  [SMALL_STATE(19)] = 1205,
  [SMALL_STATE(20)] = 1272,
  [SMALL_STATE(21)] = 1339,
  [SMALL_STATE(22)] = 1406,
  [SMALL_STATE(23)] = 1473,
  [SMALL_STATE(24)] = 1540,
  [SMALL_STATE(25)] = 1607,
  [SMALL_STATE(26)] = 1674,
  [SMALL_STATE(27)] = 1741,
  [SMALL_STATE(28)] = 1808,
  [SMALL_STATE(29)] = 1875,
  [SMALL_STATE(30)] = 1904,
  [SMALL_STATE(31)] = 1933,
  [SMALL_STATE(32)] = 1956,
  [SMALL_STATE(33)] = 1976,
  [SMALL_STATE(34)] = 1995,
  [SMALL_STATE(35)] = 2016,
  [SMALL_STATE(36)] = 2035,
  [SMALL_STATE(37)] = 2049,
  [SMALL_STATE(38)] = 2063,
  [SMALL_STATE(39)] = 2077,
  [SMALL_STATE(40)] = 2091,
  [SMALL_STATE(41)] = 2105,
  [SMALL_STATE(42)] = 2119,
  [SMALL_STATE(43)] = 2133,
  [SMALL_STATE(44)] = 2147,
  [SMALL_STATE(45)] = 2161,
  [SMALL_STATE(46)] = 2179,
  [SMALL_STATE(47)] = 2193,
  [SMALL_STATE(48)] = 2207,
  [SMALL_STATE(49)] = 2221,
  [SMALL_STATE(50)] = 2235,
  [SMALL_STATE(51)] = 2249,
  [SMALL_STATE(52)] = 2263,
  [SMALL_STATE(53)] = 2277,
  [SMALL_STATE(54)] = 2291,
  [SMALL_STATE(55)] = 2307,
  [SMALL_STATE(56)] = 2321,
  [SMALL_STATE(57)] = 2335,
  [SMALL_STATE(58)] = 2352,
  [SMALL_STATE(59)] = 2369,
  [SMALL_STATE(60)] = 2381,
  [SMALL_STATE(61)] = 2393,
  [SMALL_STATE(62)] = 2405,
  [SMALL_STATE(63)] = 2421,
  [SMALL_STATE(64)] = 2433,
  [SMALL_STATE(65)] = 2445,
  [SMALL_STATE(66)] = 2461,
  [SMALL_STATE(67)] = 2473,
  [SMALL_STATE(68)] = 2485,
  [SMALL_STATE(69)] = 2497,
  [SMALL_STATE(70)] = 2513,
  [SMALL_STATE(71)] = 2529,
  [SMALL_STATE(72)] = 2541,
  [SMALL_STATE(73)] = 2553,
  [SMALL_STATE(74)] = 2567,
  [SMALL_STATE(75)] = 2583,
  [SMALL_STATE(76)] = 2599,
  [SMALL_STATE(77)] = 2611,
  [SMALL_STATE(78)] = 2623,
  [SMALL_STATE(79)] = 2635,
  [SMALL_STATE(80)] = 2647,
  [SMALL_STATE(81)] = 2659,
  [SMALL_STATE(82)] = 2671,
  [SMALL_STATE(83)] = 2687,
  [SMALL_STATE(84)] = 2703,
  [SMALL_STATE(85)] = 2719,
  [SMALL_STATE(86)] = 2731,
  [SMALL_STATE(87)] = 2743,
  [SMALL_STATE(88)] = 2755,
  [SMALL_STATE(89)] = 2766,
  [SMALL_STATE(90)] = 2777,
  [SMALL_STATE(91)] = 2788,
  [SMALL_STATE(92)] = 2798,
  [SMALL_STATE(93)] = 2808,
  [SMALL_STATE(94)] = 2818,
  [SMALL_STATE(95)] = 2828,
  [SMALL_STATE(96)] = 2838,
  [SMALL_STATE(97)] = 2848,
  [SMALL_STATE(98)] = 2858,
  [SMALL_STATE(99)] = 2868,
  [SMALL_STATE(100)] = 2876,
  [SMALL_STATE(101)] = 2886,
  [SMALL_STATE(102)] = 2896,
  [SMALL_STATE(103)] = 2906,
  [SMALL_STATE(104)] = 2916,
  [SMALL_STATE(105)] = 2926,
  [SMALL_STATE(106)] = 2936,
  [SMALL_STATE(107)] = 2946,
  [SMALL_STATE(108)] = 2956,
  [SMALL_STATE(109)] = 2966,
  [SMALL_STATE(110)] = 2976,
  [SMALL_STATE(111)] = 2986,
  [SMALL_STATE(112)] = 2996,
  [SMALL_STATE(113)] = 3006,
  [SMALL_STATE(114)] = 3016,
  [SMALL_STATE(115)] = 3024,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continue, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_yield, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list_semicolon, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list_semicolon, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list_comma, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list_comma, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_struct, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_enum, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_let, 2, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decl_fn, 2, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_fn, 2, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_fn, 4, 0, 6),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_yield, 2, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_using, 2, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_let, 6, 0, 7),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_struct, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_enum, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_struct_body, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_enum_body, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continue, 2, 0, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_ref, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_semicolon_grouping, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_restart, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_let, 4, 0, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_let, 4, 0, 5),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_struct_body, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_list_comma_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_list_comma_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list_semicolon, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list_comma, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_list_semicolon_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_list_semicolon_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_list_semicolon_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressions, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nano(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
